# Generated by Django 2.1.1 on 2018-10-13 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0002_auto_20181014_0030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textmessage',
            old_name='msg',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='textmessage',
            old_name='name',
            new_name='talker',
        ),
    ]
